<?php
/**
 * Attain_Cookie extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Attain
 * @package    Attain_Cookie
 * @copyright  Copyright (c) 2012 Attain Design Limited
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @category   Attain
 * @package    Attain_Cookie
 * @author     Nathan Chick <nathan@attaindesign.co.uk>
 */
?>

<?
if( Mage::getStoreConfig('web/cookie/eulaw') ) {
	?>
	<p class="cookie-link"><a href="javascript:void(0);" id="attain-show-cookie">Change Cookie Settings</a></p>

	<?php  $style = Mage::getSingleton('core/cookie')->get('cookies_allowed') ? ' style="display:none;"' : ''; ?>
	<div id="attain-cookies" <?php echo $style;?>>
		<p>We would like to place cookies on your computer to help us make this website better. Data collected on this website will not be sold or used for any other purpose but to imrove your experience.</p>
		<p>Please select an option below, you can change these settings at any time on the bottom of the page.</p>
		<a href="javascript:void(0);" id="cookie-allow">Allow Cookies</a>
		<a href="javascript:void(0);" id="cookie-refuse">Refuse Cookies</a>
		<a href="javascript:void(0);" id="cookie-close">Close</a>
	</div>
	<?
}
?>